name: RFVPLauncher

options:
  deploymentTarget:
    iOS: "14.0"

settings:
  base:
    SWIFT_VERSION: "5.0"
    IPHONEOS_DEPLOYMENT_TARGET: "14.0"
    PRODUCT_BUNDLE_IDENTIFIER: com.chino.rfvp
    CODE_SIGN_STYLE: Automatic

packages:
  ZIPFoundation:
    url: https://github.com/weichsel/ZIPFoundation.git
    from: 0.9.0

targets:
  RFVPLauncher:
    type: application
    platform: iOS

    sources:
      - path: RFVPLauncher

    resources:
      - path: RFVPLauncher/Assets.xcassets
      - path: RFVPLauncher/LaunchScreen.storyboard

    info:
      path: RFVPLauncher/Info.plist

    dependencies:
      - package: ZIPFoundation
        product: ZIPFoundation
      - sdk: UIKit.framework
      - sdk: Foundation.framework
      - sdk: VideoToolbox.framework
      - sdk: CoreMedia.framework
      - sdk: CoreVideo.framework
      - sdk: AVFoundation.framework
      - sdk: Metal.framework
      - sdk: MetalKit.framework
      - sdk: QuartzCore.framework
      - sdk: CoreGraphics.framework
      - sdk: AudioToolbox.framework
      - framework: Vendor/RFVP.xcframework
        embed: false
        codeSign: false
        link: true
