#[repr(u8)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Opcode {
    Nop = 0,
    InitStack = 1,
    Call = 2,
    Syscall = 3,
    Ret = 4,
    RetV = 5,
    Jmp = 6,
    Jz = 7,
    PushNil = 8,
    PushTrue = 9,
    PushI32 = 10,
    PushI16 = 11,
    PushI8 = 12,
    PushF32 = 13,
    PushStr = 14,
    PushGlobal = 15,
    PushStack = 16,
    PushGlobalTable = 17,
    PushLocalTable = 18,
    PushTop = 19,
    PushRetValue = 20,
    PopGlobal = 21,
    LocalCopy = 22,
    PopGlobalTable = 23,
    PopLocalTable = 24,
    VmNeg = 25,
    VmAdd = 26,
    VmSub = 27,
    VmMul = 28,
    VmDiv = 29,
    VmMod = 30,
    VmBitTest = 31,
    VmAnd = 32,
    VmOr = 33,
    VmSetE = 34,
    VmSetNE = 35,
    VmSetG = 36,
    VmSetLE = 37,
    VmSetL = 38,
    VmSetGE = 39,
}

impl Opcode {
    pub fn decode(b: u8) -> Option<Self> {
        use Opcode::*;
        Some(match b {
            0 => Nop,
            1 => InitStack,
            2 => Call,
            3 => Syscall,
            4 => Ret,
            5 => RetV,
            6 => Jmp,
            7 => Jz,
            8 => PushNil,
            9 => PushTrue,
            10 => PushI32,
            11 => PushI16,
            12 => PushI8,
            13 => PushF32,
            14 => PushStr,
            15 => PushGlobal,
            16 => PushStack,
            17 => PushGlobalTable,
            18 => PushLocalTable,
            19 => PushTop,
            20 => PushRetValue,
            21 => PopGlobal,
            22 => LocalCopy,
            23 => PopGlobalTable,
            24 => PopLocalTable,
            25 => VmNeg,
            26 => VmAdd,
            27 => VmSub,
            28 => VmMul,
            29 => VmDiv,
            30 => VmMod,
            31 => VmBitTest,
            32 => VmAnd,
            33 => VmOr,
            34 => VmSetE,
            35 => VmSetNE,
            36 => VmSetG,
            37 => VmSetLE,
            38 => VmSetL,
            39 => VmSetGE,
            _ => return None,
        })
    }
}
